services:
  absensi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absensi-app
    ports:
      - "5000:5000"
    env_file:
      - packages/backend/.env
    restart: unless-stopped

    # Optional: health check
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:5000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
